# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=20)),
                ('login_date', models.DateTimeField(verbose_name='login date')),
            ],
        ),
    ]
